[project]
name = "transformers101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "protobuf>=5.29.1",
    "tiktoken>=0.8.0",
    "transformers[torch]>=4.47.0",
]
